apiVersion: v1
kind: ConfigMap
metadata:
  name: novel-pharmacy-config
data:
  NODE_ENV: "production"
  PORT: "3000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novel-pharmacy
  labels:
    app: novel-pharmacy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: novel-pharmacy
  template:
    metadata:
      labels:
        app: novel-pharmacy
    spec:
      containers:
      - name: novel-pharmacy
        image: novel-pharmacy:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: novel-pharmacy-config
        volumeMounts:
        - name: uploads-volume
          mountPath: /app/uploads
        - name: logs-volume
          mountPath: /app/logs
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/medicines
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/medicines
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: novel-pharmacy-service
  labels:
    app: novel-pharmacy
spec:
  selector:
    app: novel-pharmacy
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
